In [2]:
print("hello kalash, m jupyter UI s bol rha hu!!!")

hello kalash, m jupyter UI s bol rha hu!!!


In [3]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("C:\downs-chrome\MEGA-RECOVERYKE1Y.csv")

# Display the first 5 rows of the DataFrame
print(df)


Empty DataFrame
Columns: [r9feLg7_4ZlxjaATlQgyFA]
Index: []


In [24]:
import numpy as np

In [25]:
d1 = np.array(range(16))
print(d1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [26]:
d1.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
d1.reshape(4*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
d1 = d1.reshape(4,4)

In [29]:
d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
d1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
da1 = d1.resize(2,8)
da1

In [34]:
d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [35]:
d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [42]:
from math import sqrt
a = 8
b = 4
c = sqrt(a)
d = sqrt(b)
print(c,d)

2.8284271247461903 2.0


In [45]:
sqrt(a)

2.8284271247461903

In [7]:
import numpy as np
sl = np.array(range(16))

In [8]:
sl


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
sl.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])